package main

var seed = `
INSERT INTO "user" (
    id_user,
    internal_identifier,
    type,
    name,
    cpf,
    birth_date,
    phone_number,
    email,
    password,
    milk_donated,
    created_at,
    created_by,
    updated_at,
    updated_by,
    removed_at,
    removed_by
) VALUES
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    '234567898765435',
    'common',
    'Maria Silva',
    '47046117012',
    CURRENT_DATE - INTERVAL '20 years',
    '11999999999',
    'maria@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    2.5,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    '234567898765436',
    'common',
    'Marta Silveira',
    '72555730028',
    CURRENT_DATE - INTERVAL '30 years',
    '11999999998',
    'marta@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    5.5,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    '234567898765439',
    'adm',
    'Roberto Carlos',
    '52020984059',
    CURRENT_DATE - INTERVAL '30 years',
    '11999999997',
    'roberto@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfplNV',
    '234567898765440',
    'nurse',
    'Paula Fernandes',
    '23183437058',
    CURRENT_DATE - INTERVAL '15 years',
    '11999999996',
    'paula@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfplNV',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcNF',
    '234567898765437',
    'nurse',
    'Ana Oliveira',
    '52998224725',
    CURRENT_DATE - INTERVAL '28 years',
    '11999999979',
    'ana.enfermeira@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcNF',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcAD',
    '234567898765438',
    'adm',
    'Carlos Administrador',
    '88267441020',
    CURRENT_DATE - INTERVAL '35 years',
    '11966666666',
    'admin@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcAD',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKF',
    '234567898765441',
    'common',
    'Usuario Remover Common',
    '91556432010',
    CURRENT_DATE - INTERVAL '22 years',
    '11911112222',
    'remove.common1@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKF',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKG',
    '234567898765442',
    'common',
    'Usuario Bloqueado',
    '73492615001',
    CURRENT_DATE - INTERVAL '24 years',
    '11911113333',
    'remove.common2@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKG',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKH',
    'WORKER-DEL-001',
    'nurse',
    'Nurse Remover',
    '54839470086',
    CURRENT_DATE - INTERVAL '29 years',
    '11911114444',
    'remove.nurse@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKH',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcDR',
    '234567898765440',
    'driver',
    'Carlos Motorista',
    '15350946056',
    CURRENT_DATE - INTERVAL '35 years',
    '11999999990',
    'carlos.motorista@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcBE',
    '234567898765440',
    'common',
    'Bianca Exame',
    '15350946056',
    CURRENT_DATE - INTERVAL '28 years',
    '11999999997',
    'bianca@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcBE',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcBX',
    '234567898765441',
    'common',
    'Beatriz Exame Vencido',
    '30830143028',
    CURRENT_DATE - INTERVAL '32 years',
    '11999999996',
    'beatriz@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcBX',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcBR',
    '234567898765442',
    'common',
    'Renata Recorrente',
    '89373481070',
    CURRENT_DATE - INTERVAL '27 years',
    '11999999995',
    'renata@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcBR',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'usr_2veL1FPpuXxUaZcFaEC57BfpcBC',
    '234567898765443',
    'common',
    'Carla Coleta',
    '64723525005',
    CURRENT_DATE - INTERVAL '31 years',
    '11999999994',
    'carla@email.com',
    '2b9643d9671363af30ebed5463130ee7',
    0,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcBC',
    NULL,
    NULL,
    NULL,
    NULL
);

UPDATE "user"
SET blood_exam_valid_until = NOW() + INTERVAL '6 months'
WHERE id_user = 'usr_2veL1FPpuXxUaZcFaEC57BfpcKL';

UPDATE "user"
SET blood_exam_valid_until = NOW() - INTERVAL '1 day'
WHERE id_user = 'usr_2veL1FPpuXxUaZcFaEC57BfpcBX';

UPDATE "user"
SET blood_exam_valid_until = NOW() + INTERVAL '6 months'
WHERE id_user = 'usr_2veL1FPpuXxUaZcFaEC57BfpcBR';

INSERT INTO donation_point (
    id_donation_point,
    name,
    description,
    has_home,
    phone_number,
    email,
    opening_hours
) VALUES
(
    'dpt_2veL1FPpuXxUaZcFaEC57BfpcKE',
    'Ponto Solidário Centro',
    'Arrecadação de roupas e alimentos',
    true,
    '11999999999',
    'contato@pontosolidario.org',
    'Seg-Sex 08:00-18:00'
),
(
    'dpt_2veL1FPpuXxUaZcFaEC57BfpcMA',
    'Doa Fácil Zona Sul',
    NULL,
    false,
    NULL,
    'doafacil@email.com',
    'Seg-Sáb 09:00-17:00'
);

INSERT INTO donation (
    id_donation,
    is_active,
    user_feedback,
    created_at,
    created_by,
    updated_at,
    updated_by,
    removed_at,
    removed_by
) VALUES
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKE',
    false,
    'Doação realizada com sucesso',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKF',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfdsWG',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKG',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKH',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKI',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKJ',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcC1',
    false,
    'Doação completa para testes de contagem',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcC2',
    false,
    'Doação completa de outro usuário para testes de escopo',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKM',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKN',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKO',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKP',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKQ',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcKR',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcR1',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcR2',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcR3',
    false,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcBE',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcBE',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcBF',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcBC',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcBG',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'don_2veL1FPpuXxUaZcFaEC57BfpcBH',
    true,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
);

UPDATE donation
SET is_recurrent = true
WHERE id_donation IN (
    'don_2veL1FPpuXxUaZcFaEC57BfpcBG',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKG',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKH',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKI',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKM',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKN',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKP',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKQ'
);

INSERT INTO address (
    id_address,
    id_user,
    id_donation_point,
    zipcode,
    street,
    number,
    city,
    state,
    neighborhood,
    complement,
    latitude,
    longitude,
    created_at,
    updated_at,
    removed_at
) VALUES
(
    'adr_01JTG8J5F6W9K2M4P7Q1X8Y3ZAL',
    NULL,
    'dpt_2veL1FPpuXxUaZcFaEC57BfpcKE',
    '01310100',
    'Avenida Paulista',
    '1578',
    'São Paulo',
    'SP',
    'Bela Vista',
    'Próximo ao metrô Trianon',
    -23.561399,
    -46.656571,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7BCD',
    NULL,
    'dpt_2veL1FPpuXxUaZcFaEC57BfpcMA',
    '22250040',
    'Rua Voluntários da Pátria',
    '45',
    'Rio de Janeiro',
    'RJ',
    'Copacabana',
    'Fundos',
    -22.951916,
    -43.182482,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7MIP',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NULL,
    '09415987',
    'Rua Ribeiros dos Mares',
    '75',
    'São Bernardo do Campo',
    'SP',
    'Centro',
    'Próximo ao Hospital São Paulo',
    -27.923916,
    -46.172981,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTX0H1V8N5Q3W7E2R4T6Y8UPD',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NULL,
    '01545000',
    'Rua Teste Atualizacao',
    '101',
    'São Paulo',
    'SP',
    'Vila Mariana',
    'Casa 1',
    -23.589523,
    -46.637636,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTX0H1V8N5Q3W7E2R4T6Y8MBL',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    '01545001',
    'Rua Teste Atualizacao 2',
    '102',
    'São Paulo',
    'SP',
    'Vila Madalena',
    'Casa 5',
    -22.589923,
    -41.637736,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTX0H1V8N5Q3W7E2R4T6Y8ZXE',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NULL,
    '01546022',
    'Rua das Flores',
    '111',
    'Belo Horizonte',
    'MG',
    'Jardim América',
    'Casa 1209',
    -13.559511,
    -36.737330,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTX0H1V8N5Q3W7E2R4T6Y8ADM',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    '04538132',
    'Avenida Brigadeiro Faria Lima',
    '2000',
    'São Paulo',
    'SP',
    'Itaim Bibi',
    'Sala 10',
    -23.587421,
    -46.681521,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT1',
    NULL,
    NULL,
    '01310200',
    'Avenida Paulista',
    '900',
    'Sao Paulo',
    'SP',
    'Bela Vista',
    NULL,
    -23.563210,
    -46.654500,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT2',
    NULL,
    NULL,
    '04101300',
    'Rua Domingos de Morais',
    '1200',
    'Sao Paulo',
    'SP',
    'Vila Mariana',
    NULL,
    -23.588100,
    -46.637900,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT3',
    NULL,
    NULL,
    '05409000',
    'Rua Teodoro Sampaio',
    '2100',
    'Sao Paulo',
    'SP',
    'Pinheiros',
    NULL,
    -23.559000,
    -46.688000,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT4',
    NULL,
    NULL,
    '02011000',
    'Rua Sem Coordenadas',
    '10',
    'Sao Paulo',
    'SP',
    'Santana',
    NULL,
    NULL,
    NULL,
    NOW(),
    NULL,
    NULL
),
(
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT5',
    NULL,
    NULL,
    '22041011',
    'Avenida Atlantica',
    '1702',
    'Rio de Janeiro',
    'RJ',
    'Copacabana',
    NULL,
    -22.968700,
    -43.180500,
    NOW(),
    NULL,
    NULL
);

INSERT INTO user_baby (
    id_user_baby,
    id_user,
    name,
    birth_date,
    created_at,
    updated_at,
    removed_at
)
VALUES
(
    'usb_01JTG8J5F6W9K2M4P7Q1X8Y3ZAL',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    'Miguel',
    '2025-01-15 08:30:00',
    NOW(),
    NULL,
    NULL
),
(
    'usb_01JTG8K8N4P2R6T9V1X3Y5Z7BCD',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    'Helena',
    '2024-11-02 14:10:00',
    NOW(),
    NULL,
    NULL
),
(
    'usb_01JTG8K8N4P2R6T9V1X3Y5Z7DEL',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    'Baby Para Deletar',
    '2025-06-01 00:00:00',
    NOW(),
    NULL,
    NULL
),
(
    'usb_01JTG8K8N4P2R6T9V1X3Y5Z7MIP',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    'Arthur',
    '2025-03-20 06:45:00',
    NOW(),
    NULL,
    NULL
);

INSERT INTO donation_step (
    id_donation_step,
    id_donation,
    id_address,
    name,
    description,
    status,
    set_date,
    created_at,
    created_by,
    updated_at,
    updated_by,
    completed_at
) VALUES
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcAA',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NULL,
    'Exame de sangue',
    'Coleta agendada com o doador',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcBB',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKF',
    NULL,
    'Entregar kit de ordenha',
    'Entregar kit de ordenha ao doador',
    'review',
    NOW() + INTERVAL '3 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcCC',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKF',
    NULL,
    'Coletar leite',                          -- ← corrigido
    'Step reservado para testes de criação de job',
    'pending',
    NOW() + INTERVAL '5 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcAD',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcDD',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKJ',
    NULL,
    'Análise de leite',
    'Step finalizado para testes de atualização',
    'done',
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '2 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcAD',
    NOW() - INTERVAL '1 day',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcAD',
    NOW() - INTERVAL '1 day'
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcEE',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKJ',
    NULL,
    'Coletar leite',
    'Realizar coleta na residência da doadora',
    'pending',
    NOW() + INTERVAL '7 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcAD',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcFF',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKJ',
    NULL,
    'Entregar kit de ordenha',
    'Entregar kit de coleta ao doador',
    'pending',
    NOW() + INTERVAL '5 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcAD',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfslJG',
    'don_2veL1FPpuXxUaZcFaEC57BfdsWG',
    NULL,
    'Entregar kit de ordenha',
    'Entregar kit de ordenha ao doador',
    'review',
    NOW() + INTERVAL '3 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcG1',
    'don_2veL1FPpuXxUaZcFaEC57BfpcC1',
    NULL,
    'Exame de sangue',
    'Exame realizado com sucesso',
    'done',
    NOW() - INTERVAL '4 days',
    NOW() - INTERVAL '5 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NOW() - INTERVAL '4 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NOW() - INTERVAL '4 days'
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcG2',
    'don_2veL1FPpuXxUaZcFaEC57BfpcC1',
    NULL,
    'Entregar kit de ordenha',
    'Kit entregue ao doador',
    'done',
    NOW() - INTERVAL '3 days',
    NOW() - INTERVAL '4 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NOW() - INTERVAL '3 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NOW() - INTERVAL '3 days'
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcG3',
    'don_2veL1FPpuXxUaZcFaEC57BfpcC1',
    NULL,
    'Coletar leite',
    'Coleta realizada com sucesso',
    'done',
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '3 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NOW() - INTERVAL '2 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NOW() - INTERVAL '2 days'
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcG4',
    'don_2veL1FPpuXxUaZcFaEC57BfpcC1',
    NULL,
    'Análise de leite',
    'Análise concluída com sucesso',
    'done',
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '2 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NOW() - INTERVAL '1 day',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NOW() - INTERVAL '1 day'
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcH1',
    'don_2veL1FPpuXxUaZcFaEC57BfpcC2',
    NULL,
    'Exame de sangue',
    'Exame realizado com sucesso',
    'done',
    NOW() - INTERVAL '4 days',
    NOW() - INTERVAL '5 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NOW() - INTERVAL '4 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NOW() - INTERVAL '4 days'
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcH2',
    'don_2veL1FPpuXxUaZcFaEC57BfpcC2',
    NULL,
    'Entregar kit de ordenha',
    'Kit entregue ao doador',
    'done',
    NOW() - INTERVAL '3 days',
    NOW() - INTERVAL '4 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NOW() - INTERVAL '3 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NOW() - INTERVAL '3 days'
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcH3',
    'don_2veL1FPpuXxUaZcFaEC57BfpcC2',
    NULL,
    'Coletar leite',
    'Coleta realizada com sucesso',
    'done',
    NOW() - INTERVAL '2 days',
    NOW() - INTERVAL '3 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NOW() - INTERVAL '2 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NOW() - INTERVAL '2 days'
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcH4',
    'don_2veL1FPpuXxUaZcFaEC57BfpcC2',
    NULL,
    'Análise de leite',
    'Análise concluída com sucesso',
    'done',
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '2 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NOW() - INTERVAL '1 day',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NOW() - INTERVAL '1 day'
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcII',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKO',
    NULL,
    'Exame de sangue',
    'Step reservado para testes de atualização de endereço',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcJJ',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKO',
    NULL,
    'Entregar kit de ordenha',
    'Step reservado para testes de criação de endereço via CEP',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcKK',
    'don_2veL1FPpuXxUaZcFaEC57BfpcKR',
    NULL,
    'Coletar leite',
    'Step reservado para testes de nome duplicado na criação',
    'done',
    NOW() - INTERVAL '1 day',
    NOW() - INTERVAL '2 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NOW() - INTERVAL '1 day',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NOW() - INTERVAL '1 day'
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcR1',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR1',
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT1',
    'Coletar leite',
    'Parada de rota na Avenida Paulista',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcR2',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR2',
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT2',
    'Coletar leite',
    'Parada de rota na Vila Mariana',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcR3',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR2',
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT3',
    'Entregar kit de ordenha',
    'Parada de rota em Pinheiros',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcR4',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR3',
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT1',
    'Coletar leite',
    'Parada de rota de doacao inativa',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcR5',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR1',
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT4',
    'Entregar kit de ordenha',
    'Parada de rota sem coordenadas',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcR6',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR2',
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT5',
    'Coletar leite',
    'Parada de rota fora de Sao Paulo',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57Bfpd54',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR1',
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT1',
    'Coletar leite',
    'Parada de rota ja vinculada a uma rota ativa (fixture)',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57Bfpd55',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR1',
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT2',
    'Coletar leite',
    'Parada de rota ja vinculada a uma rota ativa (fixture)',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57Bfpd56',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR1',
    'adr_01JTG8K8N4P2R6T9V1X3Y5Z7RT3',
    'Coletar leite',
    'Parada de rota ja vinculada a uma rota ativa (fixture)',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57Bfpd57',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR1',
    NULL,
    'Coletar leite',
    'Etapa de doacao ativa porem sem endereco (fixture)',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
),
(
    'dst_2veL1FPpuXxUaZcFaEC57BfpcBF',
    'don_2veL1FPpuXxUaZcFaEC57BfpcBF',
    NULL,
    'Exame de sangue',
    'Step reservado para testes de conclusao do exame de sangue',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL
);

INSERT INTO bottle (
    id_bottle,
    id_donation,
    quantity_donated_ml,
    discarded,
    description,
    created_at,
    created_by
) VALUES
(
    'btl_2veL1FPpuXxUaZcFaEC57BfpcB1',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR1',
    150.50,
    false,
    'Frasco coletado na Avenida Paulista',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS'
),
(
    'btl_2veL1FPpuXxUaZcFaEC57BfpcB2',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR1',
    200.00,
    NULL,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS'
),
(
    'btl_2veL1FPpuXxUaZcFaEC57BfpcB3',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR2',
    300.00,
    false,
    'Frasco coletado na Vila Mariana',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS'
),
(
    'btl_2veL1FPpuXxUaZcFaEC57BfpcB4',
    'don_2veL1FPpuXxUaZcFaEC57BfpcR2',
    80.00,
    true,
    'Frasco descartado por contaminacao',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS'
);

INSERT INTO donation_step_timeline (
    id_donation_step_timeline,
    id_donation_step,
    description,
    status,
    set_date,
    created_at,
    created_by
) VALUES
(
    'dtl_2veL1FPpuXxUaZcFaEC57BfpcAA',
    'dst_2veL1FPpuXxUaZcFaEC57BfpcAA',
    'Timeline entry 1 - Exame agendado',
    'pending',
    NOW() + INTERVAL '2 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL'
),
(
    'dtl_2veL1FPpuXxUaZcFaEC57BfpcBB',
    'dst_2veL1FPpuXxUaZcFaEC57BfpcAA',
    'Timeline entry 2 - Exame realizado',
    'done',
    NOW() + INTERVAL '3 days',
    NOW() + INTERVAL '1 day',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL'
);

INSERT INTO job (
    id_job,
    id_user,
    id_step,
    status,
    name,
    description,
    date_set,
    user_feedback,
    created_at,
    created_by,
    updated_at,
    updated_by,
    removed_at,
    removed_by
) VALUES
(
    'job_2veL1FPpuXxUaZcFaEC57Bfpc01',
    'usr_2veL1FPpuXxUaZcFaEC57BfplNV',
    'dst_2veL1FPpuXxUaZcFaEC57BfpcAA',
    'done',
    'Entrega ao ponto',
    'Transporte do material para o ponto de coleta',
    CURRENT_DATE + INTERVAL '2 days',
    'Coleta realizada com sucesso',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKE',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfplNV',
    NULL,
    NULL
),
(
    'job_2veL1FPpuXxUaZcFaEC57Bfpc02',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    'dst_2veL1FPpuXxUaZcFaEC57BfpcBB',
    'pending',
    'Análise laboratorial',
    'Analisar e aprovar amostras',
    CURRENT_DATE + INTERVAL '4 days',
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcKL',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'job_3EEMMlZS3VexkBHkGHPjq0Qt86V',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcNF',
    'dst_2veL1FPpuXxUaZcFaEC57BfpcEE',
    'pending',
    'Coleta domiciliar',
    'Realizar coleta na residência da doadora',
    CURRENT_DATE + INTERVAL '7 days',
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcAD',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'job_3EEP6m8y0peA0J6lrNABYPhhJzG',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcNF',
    'dst_2veL1FPpuXxUaZcFaEC57BfpcFF',
    'pending',
    'Entrega de material',
    'Entregar kit de coleta ao doador',
    CURRENT_DATE + INTERVAL '5 days',
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcAD',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'job_2veL1FPpuXxUaZcFaEC57Bfpc03',
    'usr_2veL1FPpuXxUaZcFaEC57BfplNV',
    'dst_2veL1FPpuXxUaZcFaEC57BfpcR1',
    'pending',
    'Coleta da rota concluida',
    'Job ativo da enfermeira sobre uma etapa que e parada de rota (fixture)',
    CURRENT_DATE + INTERVAL '3 days',
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpcAD',
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO route (
    id_route,
    id_driver,
    name,
    description,
    user_feedback,
    city,
    neighborhood,
    status,
    date_start,
    date_end,
    mileage,
    date_set,
    created_at,
    created_by,
    updated_at,
    updated_by,
    removed_at,
    removed_by
) VALUES
(
    'rot_3Idl55gnHyIrunoK64VSS5XX6Rg',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcDR',
    'Rota Centro-Sul concluida',
    'Coleta na Avenida Paulista e na Vila Mariana',
    'Rota concluida sem intercorrencias, doadoras presentes no horario',
    'Sao Paulo',
    'Bela Vista',
    'done',
    NOW() - INTERVAL '5 days' + INTERVAL '8 hours',
    NOW() - INTERVAL '5 days' + INTERVAL '11 hours',
    38.40,
    NOW() - INTERVAL '5 days',
    NOW() - INTERVAL '6 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NOW() - INTERVAL '5 days' + INTERVAL '11 hours',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcDR',
    NULL,
    NULL
),
(
    'rot_3Idl53RaMuX0ZMiITkgCEcPBiZq',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcDR',
    'Rota Oeste-Norte em andamento',
    'Coleta em Pinheiros com entrega de kit em Santana',
    NULL,
    'Sao Paulo',
    'Pinheiros',
    'in_progress',
    NOW() - INTERVAL '2 hours',
    NULL,
    NULL,
    NOW(),
    NOW() - INTERVAL '1 day',
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NOW() - INTERVAL '2 hours',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcDR',
    NULL,
    NULL
),
(
    'rot_3Idl54wck70MCPRK5i7rViCNvwO',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcDR',
    'Rota Copacabana agendada',
    'Coleta agendada na Avenida Atlantica',
    NULL,
    'Rio de Janeiro',
    'Copacabana',
    'pending',
    NULL,
    NULL,
    NULL,
    NOW() + INTERVAL '3 days',
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL,
    NULL
);

INSERT INTO route_donation_step (
    id_route_donation_step,
    id_route,
    id_donation_step,
    stop_order,
    date_start,
    date_end,
    created_at,
    created_by,
    updated_at,
    updated_by,
    removed_at,
    removed_by
) VALUES
(
    'rds_3Idl54SAt7SBYcutzdS6MYaKViF',
    'rot_3Idl55gnHyIrunoK64VSS5XX6Rg',
    'dst_2veL1FPpuXxUaZcFaEC57BfpcR1',
    0,
    NOW() - INTERVAL '5 days' + INTERVAL '8 hours',
    NOW() - INTERVAL '5 days' + INTERVAL '9 hours',
    NOW() - INTERVAL '6 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NOW() - INTERVAL '5 days' + INTERVAL '9 hours',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcDR',
    NULL,
    NULL
),
(
    'rds_3Idl53TDdo3E18YXp3pAacU89zi',
    'rot_3Idl55gnHyIrunoK64VSS5XX6Rg',
    'dst_2veL1FPpuXxUaZcFaEC57BfpcR2',
    1,
    NOW() - INTERVAL '5 days' + INTERVAL '10 hours',
    NOW() - INTERVAL '5 days' + INTERVAL '11 hours',
    NOW() - INTERVAL '6 days',
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NOW() - INTERVAL '5 days' + INTERVAL '11 hours',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcDR',
    NULL,
    NULL
),
(
    'rds_3Idl50yWGFGbXMnMxn4t9MKpqqe',
    'rot_3Idl53RaMuX0ZMiITkgCEcPBiZq',
    'dst_2veL1FPpuXxUaZcFaEC57Bfpd54',
    0,
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '1 hour',
    NOW() - INTERVAL '1 day',
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NOW() - INTERVAL '1 hour',
    'usr_2veL1FPpuXxUaZcFaEC57BfpcDR',
    NULL,
    NULL
),
(
    'rds_3Idl56YdFkFfaGRvGueGauyvH4t',
    'rot_3Idl53RaMuX0ZMiITkgCEcPBiZq',
    'dst_2veL1FPpuXxUaZcFaEC57Bfpd55',
    1,
    NULL,
    NULL,
    NOW() - INTERVAL '1 day',
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    'rds_3Idl5682G71NpyWcLO11dpwnX59',
    'rot_3Idl54wck70MCPRK5i7rViCNvwO',
    'dst_2veL1FPpuXxUaZcFaEC57Bfpd56',
    0,
    NULL,
    NULL,
    NOW(),
    'usr_2veL1FPpuXxUaZcFaEC57BfpxWS',
    NULL,
    NULL,
    NULL,
    NULL
);
`
